### ISSUE TITLE
Tweet Feed Fail: You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints

### ISSUE THREAD

**Issue by nattywebdev** [backdrop-contrib/tweet_feed#6]
As of a few days ago I am seeing this error and a failure to pull in tweets:

Tweet Feed Fail: You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product: 453

Is this because of a change at the Twitter end? If so can anything be done to update the tweet_feed module? Or does this depend (as suggested) on a higher access level (presumably meaning 'paid') at the Twitter end?

**Comment by klonos** [comment]
As @indigoxela mentioned in the [Zulip chat](https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Tweet.20Feed/near/381893374) about this:

> As far as I know, the Twitter (or "X") API is mostly dead. Free access has been dropped earlier this year. That caused some riot in the news, but that didn't change anything. There's nothing, the module can do about that.

To which I said this:

>> There's nothing, the module can do about that.
>
> We can add a notice in the README of the module, explaining that the "Twitter API is mostly dead and there's nothing we can do about that" and to ask people to not use it until further notice. Perhaps also a new release of the module that throws a status page notice?

**Comment by klonos** [comment]
@ElusiveMind are you still around and have capacity to do any of this?

**Comment by ElusiveMind** [comment]
I am. I can add this. I've had to drop support of this for the time being hoping to find a work around, but X has made it pretty difficult for me to develop for it since I refuse to pay for a developer license to continue testing. I'll add this to a list of items to do for Drupal and Backdrop in the next week-10 days.

**Comment by ElusiveMind** [comment]
This notice has been added to the module information page. It is also added to the status page as a notice.

**Comment by nattywebdev** [comment]
Understood. Thank you for clarifying.
